from ggdb import db

class Combo(db.Model):
	id = 		db.Column(db.Integer, primary_key=True)
	verifier_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
	charspecs_id = 	db.Column(db.Integer, db.ForeignKey('charspecs.id'), nullable=False)
	character = db.Column(db.Integer, nullable=False)
	combo = 	db.Column(db.Integer, unique=True, nullable=False)
	damage = 	db.Column(db.Integer, nullable=True)
	standing = 	db.Column(db.Boolean, nullable=False)
	crouching = db.Column(db.Boolean, nullable=False)
	jumping = 	db.Column(db.Boolean, nullable=False)
	midscreen = db.Column(db.Boolean, nullable=False)
	nearcorner = db.Column(db.Boolean, nullable=False)
	corner = 	db.Column(db.Boolean, nullable=False)
	meter = 	db.Column(db.Integer, nullable=False)
	comment = 	db.Column(db.String(1000), nullable=True)
	video = 	db.Column(db.String(60), nullable=True)


class CharSpecs(db.Model):
	id = 		db.Column(db.Integer, primary_key=True)
	characters = db.relationship('Combo', backref='associated_combos', lazy=True)
	sol = 		db.Column(db.Boolean, nullable=False)
	ky = 		db.Column(db.Boolean, nullable=False)
	may = 		db.Column(db.Boolean, nullable=False)
	millia = 	db.Column(db.Boolean, nullable=False)
	zato1 = 	db.Column(db.Boolean, nullable=False)
	potemkin = 	db.Column(db.Boolean, nullable=False)
	chipp = 	db.Column(db.Boolean, nullable=False)
	faust = 	db.Column(db.Boolean, nullable=False)
	axl = 		db.Column(db.Boolean, nullable=False)
	venom = 	db.Column(db.Boolean, nullable=False)
	slayer = 	db.Column(db.Boolean, nullable=False)
	ino = 		db.Column(db.Boolean, nullable=False)
	bedman = 	db.Column(db.Boolean, nullable=False)
	ramlethal = db.Column(db.Boolean, nullable=False)
	sin = 		db.Column(db.Boolean, nullable=False)
	elphelt = 	db.Column(db.Boolean, nullable=False)
	leo = 		db.Column(db.Boolean, nullable=False)
	johnny = 	db.Column(db.Boolean, nullable=False)
	jacko = 	db.Column(db.Boolean, nullable=False)
	jam = 		db.Column(db.Boolean, nullable=False)
	kum = 		db.Column(db.Boolean, nullable=False)
	raven = 	db.Column(db.Boolean, nullable=False)
	dizzy = 	db.Column(db.Boolean, nullable=False)
	baiken = 	db.Column(db.Boolean, nullable=False)
	answer = 	db.Column(db.Boolean, nullable=False)